import { service as authService } from "./controllers/auth/index";
import { service as verifyRecaptchaService } from "./controllers/VerifyRecaptcha/index";
// import { service as announcementsService } from "./controllers/announcements-api/index";
import { service as applicantsService } from "./controllers/applicants/index";
import { service as applicationService } from "./controllers/application/index";
// import { service as analyticsService } from "./controllers/analytics/index";
// import { service as writeToAnalyticService } from "./controllers/analytics/index";
import { service as emailService } from "./controllers/email/index";
import { service as hackerService } from "./controllers/hacker/index";
import { service as adminService } from "./controllers/admin/index";
import { service as cruzpointsService } from "./controllers/cruzpoints/index";
import { service as teamsService } from "./controllers/teams/index";
// import { service as notifyService } from "./controllers/notify/index";

export const auth = authService;
export const verifyRecaptcha = verifyRecaptchaService;
// export const announcements = announcementsService;
export const applicants = applicantsService;
export const application = applicationService;
// export const analytics = analyticsService;
// export const writeToAnalytics = writeToAnalyticService;
export const email = emailService;
export const hacker = hackerService;
export const admin = adminService;
export const cruzpoints = cruzpointsService;
export const teams = teamsService;
// export const notify = notifyService;
